# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

contact_links:
  - name: ๐ฌ ุจุญุซ ุนููู
    url: https://github.com/teal33t/The-Bad-Branch/discussions
    about: ุจุฑุง ุจุญุซโูุง ฺฉู ู ฺฏูพ ู ฺฏูุชุ ูุทูุงู ุงุฒ ุจุฎุด Discussions ุงุณุชูุงุฏู ฺฉูุฏ.

issue_templates:
  - name: "๐ ุซุจุช ฺฏุฒุงุฑุด ุฌุฏุฏ"
    description: "ูุนุฑู ฺฉ ุฏูุฑูุ ุดุฎุต ุง ููุณุณู ุจุฑุง ุจุฑุฑุณ"
    title: "[ฺฏุฒุงุฑุด]: "
    labels: ["ฺฏุฒุงุฑุด-ุฌุฏุฏ", "ูุงุฒ-ุจู-ุจุฑุฑุณ"]
    body: ./new_report.md

  - name: "๐ฌ ุฏุฑุฎูุงุณุช ุงุตูุงุญ ุง ูพุงุณุฎฺฏู"
    description: "ุงฺฏุฑ ูุงู ุดูุง ุฏุฑ ฺฏุฒุงุฑุด ุขูุฏู ู ูโุฎูุงูุฏ ูพุงุณุฎ ุฏูุฏ ุง ุงุทูุงุนุงุช ุฑุง ุงุตูุงุญ ฺฉูุฏ"
    title: "[ูพุงุณุฎ/ุงุตูุงุญ]: "
    labels: ["ูพุงุณุฎ", "ุจุญุซ"]
    body: ./correction_request.md

  - name: "๐ก ูพุฑุณุด ุนููู ุง ูพุดููุงุฏ"
    description: "ุงฺฏุฑ ุณูุงู ุฏุฑ ููุฑุฏ ุฎูุฏ ูพุฑูฺู ุฏุงุฑุฏ ุง ูโุฎูุงูุฏ ูพุดููุงุฏ ุจุฑุง ุจูุจูุฏ ุขู ุงุฑุงุฆู ุฏูุฏ"
    title: "[ูพุฑุณุด]: "
    labels: ["ุณูุงู"]
    body: ./general_question.md